// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime DateAdded { get; set; }

    public Guid PersonaId { get; set; }

    public string Password { get; set; }

    public virtual Persona Persona { get; set; }
}