// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class BastionActivityHireling
{
    public Guid Id { get; set; }

    public Guid ActivityId { get; set; }

    public Guid BastionHirelingId { get; set; }

    public DateTime DateAdded { get; set; }

    public virtual BastionActivity Activity { get; set; }

    public virtual BastionHireling BastionHireling { get; set; }
}