// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class BastionRoom
{
    public Guid Id { get; set; }

    public Guid BastionId { get; set; }

    public string Kind { get; set; }

    public Guid? BastionFacilityId { get; set; }

    public string Name { get; set; }

    public string SpaceSize { get; set; }

    public int OriginX { get; set; }

    public int OriginY { get; set; }

    public string GeometryJson { get; set; }

    public string Color { get; set; }

    public int? MaxConcurrentActivities { get; set; }

    public byte[] RowVersion { get; set; }

    public int FloorLevel { get; set; }

    public virtual CampaignBastion Bastion { get; set; }

    public virtual ICollection<BastionActivity> BastionActivities { get; set; } = new List<BastionActivity>();

    public virtual BastionFacility BastionFacility { get; set; }

    public virtual ICollection<BastionHireling> BastionHirelings { get; set; } = new List<BastionHireling>();
}