// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class BastionAccessLevel
{
    public byte Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<UserBastion> UserBastions { get; set; } = new List<UserBastion>();
}