// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class BastionActivity
{
    public Guid Id { get; set; }

    public Guid SegmentId { get; set; }

    public Guid CharacterId { get; set; }

    public Guid BastionRoomId { get; set; }

    public string ActionKind { get; set; }

    public string OrderType { get; set; }

    public string Title { get; set; }

    public int TurnsCost { get; set; }

    public int LongRestsCost { get; set; }

    public int? StartDay { get; set; }

    public int DurationDays { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public string ResultSummary { get; set; }

    public Guid CreatedByUserId { get; set; }

    public DateTime DateAdded { get; set; }

    public DateTime? DateUpdated { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<BastionActivityHireling> BastionActivityHirelings { get; set; } = new List<BastionActivityHireling>();

    public virtual BastionRoom BastionRoom { get; set; }

    public virtual Character Character { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual BastionTurnSegment Segment { get; set; }
}