// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class BastionHireling
{
    public Guid Id { get; set; }

    public Guid? BastionRoomId { get; set; }

    public string Name { get; set; }

    public string Role { get; set; }

    public string Notes { get; set; }

    public bool IsAbsent { get; set; }

    public int SortOrder { get; set; }

    public DateTime DateAdded { get; set; }

    public byte[] RowVersion { get; set; }

    public Guid CampaignId { get; set; }

    public virtual ICollection<BastionActivityHireling> BastionActivityHirelings { get; set; } = new List<BastionActivityHireling>();

    public virtual BastionRoom BastionRoom { get; set; }

    public virtual Campaign Campaign { get; set; }
}