// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class BastionTurnSegment
{
    public Guid Id { get; set; }

    public Guid BastionId { get; set; }

    public Guid IssuedByUserId { get; set; }

    public string Title { get; set; }

    public int TurnsGranted { get; set; }

    public int DaysGranted { get; set; }

    public byte LongRestsPerDay { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public DateTime DateIssued { get; set; }

    public DateTime? DateConcluded { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual CampaignBastion Bastion { get; set; }

    public virtual ICollection<BastionActivity> BastionActivities { get; set; } = new List<BastionActivity>();

    public virtual ICollection<BastionActivityLog> BastionActivityLogs { get; set; } = new List<BastionActivityLog>();

    public virtual ICollection<BastionTurnSegmentCharacter> BastionTurnSegmentCharacters { get; set; } = new List<BastionTurnSegmentCharacter>();

    public virtual User IssuedByUser { get; set; }
}