// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class BastionActivityLog
{
    public Guid Id { get; set; }

    public Guid SegmentId { get; set; }

    public Guid? ActivityId { get; set; }

    public Guid? CharacterId { get; set; }

    public Guid? ByUserId { get; set; }

    public string Action { get; set; }

    public string Detail { get; set; }

    public DateTime DateAdded { get; set; }

    public virtual BastionTurnSegment Segment { get; set; }
}