// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class BastionFloor
{
    public Guid Id { get; set; }

    public Guid BastionId { get; set; }

    public int Level { get; set; }

    public string Name { get; set; }

    public DateTime DateAdded { get; set; }

    public virtual CampaignBastion Bastion { get; set; }
}