// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class BastionFacility
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string FacilityType { get; set; }

    public int? LevelRequired { get; set; }

    public string SpaceJson { get; set; }

    public string HirelingsJson { get; set; }

    public string OrdersJson { get; set; }

    public string PrerequisiteJson { get; set; }

    public string DescriptionMarkdown { get; set; }

    public string SourceBook { get; set; }

    public int? Page { get; set; }

    public DateTime DateAdded { get; set; }

    public virtual ICollection<BastionRoom> BastionRooms { get; set; } = new List<BastionRoom>();
}