// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class CampaignCategoryContentXref
{
    public Guid Id { get; set; }

    public Guid CampaignId { get; set; }

    public Guid? ParentContentId { get; set; }

    public Guid? CreatorId { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public int AccessHierarchyLevel { get; set; }

    public string ContentLink { get; set; }

    public string IconLink { get; set; }

    public string SimpleContent { get; set; }

    public Guid? ContentTypeId { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual ContentType ContentType { get; set; }
}