// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Data.Models
{
    public partial class CampaignManagerContext
    {
        private ICampaignManagerContextProcedures _procedures;

        public virtual ICampaignManagerContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CampaignManagerContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICampaignManagerContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class CampaignManagerContextProcedures : ICampaignManagerContextProcedures
    {
        private readonly CampaignManagerContext _context;

        public CampaignManagerContextProcedures(CampaignManagerContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetCampaignPersonaResult>> GetCampaignPersonaAsync(Guid? userId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UserId",
                    Value = userId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetCampaignPersonaResult>("EXEC @returnValue = [dbo].[GetCampaignPersona] @UserId = @UserId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
