// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

public partial class CampaignManagerContext : DbContext
{
    public CampaignManagerContext(DbContextOptions<CampaignManagerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Campaign> Campaigns { get; set; }

    public virtual DbSet<CampaignCategoryContentXref> CampaignCategoryContentXrefs { get; set; }

    public virtual DbSet<CampaignPersona> CampaignPersonas { get; set; }

    public virtual DbSet<SitePersona> SitePersonas { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserCampaignPersona> UserCampaignPersonas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Campaign>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Campaign__3214EC07783CDB57");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250);
        });

        modelBuilder.Entity<CampaignCategoryContentXref>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Campaign__3214EC07C8D79780");

            entity.ToTable("CampaignCategoryContentXREF");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.DisplayName).IsRequired();

            entity.HasOne(d => d.Campaign).WithMany(p => p.CampaignCategoryContentXrefs)
                .HasForeignKey(d => d.CampaignId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CampaignC__Campa__160F4887");
        });

        modelBuilder.Entity<CampaignPersona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Campaign__3214EC07B03C0EB5");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(120);

            entity.HasOne(d => d.Campaign).WithMany(p => p.CampaignPersonas)
                .HasForeignKey(d => d.CampaignId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CampaignP__Campa__6FE99F9F");
        });

        modelBuilder.Entity<SitePersona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Personas__3214EC07D18E55D5");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(120);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC075D23BCD5");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.FirstName).HasMaxLength(120);
            entity.Property(e => e.LastName).HasMaxLength(120);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.Persona).WithMany(p => p.Users)
                .HasForeignKey(d => d.PersonaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__PersonaId__4222D4EF");
        });

        modelBuilder.Entity<UserCampaignPersona>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.CampaignPersonaId });

            entity.HasOne(d => d.CampaignPersona).WithMany(p => p.UserCampaignPersonas)
                .HasForeignKey(d => d.CampaignPersonaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserCampa__Campa__03F0984C");

            entity.HasOne(d => d.User).WithMany(p => p.UserCampaignPersonas)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserCampa__UserI__02FC7413");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}