// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class CampaignPersona
{
    public Guid Id { get; set; }

    public string DisplayName { get; set; }

    public Guid CampaignId { get; set; }

    public int Hierarchy { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual ICollection<UserCampaignPersona> UserCampaignPersonas { get; set; } = new List<UserCampaignPersona>();
}