// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class CampaignBastion
{
    public Guid Id { get; set; }

    public Guid CampaignId { get; set; }

    public string Name { get; set; }

    public int MaxWidth { get; set; }

    public int MaxHeight { get; set; }

    public int CurrentTurn { get; set; }

    public bool IsActive { get; set; }

    public Guid CreatedByUserId { get; set; }

    public DateTime DateAdded { get; set; }

    public byte[] RowVersion { get; set; }

    public string SettingsJson { get; set; }

    public virtual ICollection<BastionCharacter> BastionCharacters { get; set; } = new List<BastionCharacter>();

    public virtual ICollection<BastionFloor> BastionFloors { get; set; } = new List<BastionFloor>();

    public virtual ICollection<BastionRoom> BastionRooms { get; set; } = new List<BastionRoom>();

    public virtual ICollection<BastionTurnSegment> BastionTurnSegments { get; set; } = new List<BastionTurnSegment>();

    public virtual Campaign Campaign { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual ICollection<UserBastion> UserBastions { get; set; } = new List<UserBastion>();
}