// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Character
{
    public Guid Id { get; set; }

    public Guid CampaignId { get; set; }

    public Guid? UserId { get; set; }

    public string Name { get; set; }

    public string Notes { get; set; }

    public bool IsActive { get; set; }

    public int SortOrder { get; set; }

    public DateTime DateAdded { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<BastionActivity> BastionActivities { get; set; } = new List<BastionActivity>();

    public virtual ICollection<BastionCharacter> BastionCharacters { get; set; } = new List<BastionCharacter>();

    public virtual ICollection<BastionTurnSegmentCharacter> BastionTurnSegmentCharacters { get; set; } = new List<BastionTurnSegmentCharacter>();

    public virtual Campaign Campaign { get; set; }

    public virtual User User { get; set; }
}