// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class ContentType
{
    public Guid Id { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public virtual ICollection<CampaignCategoryContentXref> CampaignCategoryContentXrefs { get; set; } = new List<CampaignCategoryContentXref>();
}