// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Models
{
    public partial class GetCampaignPersonaResult
    {
        public Guid CampaignPersonaId { get; set; }
        [StringLength(120)]
        public string CampaignPersonaName { get; set; }
        public int Hierarchy { get; set; }
        public Guid CampaignId { get; set; }
        [StringLength(2147483647)]
        public string CampaignDescription { get; set; }
        [StringLength(250)]
        public string CampaignName { get; set; }
    }
}
