// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Permission
{
    public Guid Id { get; set; }

    public string DisplayName { get; set; }

    public bool CampaignAssignable { get; set; }

    public virtual ICollection<CampaignPersonaPermission> CampaignPersonaPermissions { get; set; } = new List<CampaignPersonaPermission>();
}