// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class UserBastion
{
    public Guid Id { get; set; }

    public Guid BastionId { get; set; }

    public Guid UserId { get; set; }

    public byte BastionAccessLevelId { get; set; }

    public DateTime DateAdded { get; set; }

    public virtual CampaignBastion Bastion { get; set; }

    public virtual BastionAccessLevel BastionAccessLevel { get; set; }

    public virtual User User { get; set; }
}