// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class UserCampaignPersona
{
    public Guid UserId { get; set; }

    public Guid CampaignPersonaId { get; set; }

    public virtual CampaignPersona CampaignPersona { get; set; }

    public virtual User User { get; set; }
}