// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime DateAdded { get; set; }

    public Guid PersonaId { get; set; }

    public string Password { get; set; }

    public bool IsVerified { get; set; }

    public virtual ICollection<BastionActivity> BastionActivities { get; set; } = new List<BastionActivity>();

    public virtual ICollection<BastionTurnSegment> BastionTurnSegments { get; set; } = new List<BastionTurnSegment>();

    public virtual ICollection<CampaignBastion> CampaignBastions { get; set; } = new List<CampaignBastion>();

    public virtual ICollection<Character> Characters { get; set; } = new List<Character>();

    public virtual SitePersona Persona { get; set; }

    public virtual ICollection<UserBastion> UserBastions { get; set; } = new List<UserBastion>();

    public virtual ICollection<UserCampaignPersona> UserCampaignPersonas { get; set; } = new List<UserCampaignPersona>();
}